### ISSUE TITLE
Label customizeds

### ISSUE THREAD

**Issue by Lowpoc** [marxjmoura/admin4b#20]
Hi marx, 

i maked a label customized , follow the code font:

```
.label {
    display: inline;
    padding: .2em .6em .3em;
    font-size: 75%;
    font-weight: 700;
    line-height: 1;
    color: #fff;
    text-align: center;
    white-space: nowrap;
    vertical-align: baseline;
    border-radius: .25em;
}
.label-danger {
    background-color: #d9534f;
}

.label-info {
    background-color: #007bff;
}

.label-success {
    background-color: #28a745;
} 
.label-default {
  background-color: #808080;
}
```
### How use
```
<span class="label label-danger text-uppercase">
 Não comercializado
</span>
```

### Result

![label-danger](https://user-images.githubusercontent.com/17841549/36545366-81404d82-17c7-11e8-9212-32f269a8be7b.png)
![label-default](https://user-images.githubusercontent.com/17841549/36545369-82307744-17c7-11e8-8e77-98c5a6e0a2dc.png)
![label-info](https://user-images.githubusercontent.com/17841549/36545371-8362a75e-17c7-11e8-90cf-689f10d40325.png)
![label-success](https://user-images.githubusercontent.com/17841549/36545375-846e2f10-17c7-11e8-916b-3f3539b33f50.png)

**Comment by marxjmoura** [comment]
Nice! But there is the [badge](https://getbootstrap.com/docs/4.0/components/badge/) component in Bootstrap 4 for the same purpose. So I will close the issue.
