### ISSUE TITLE
Gradient has outdated direction syntax.

### ISSUE THREAD

**Issue by Lowpoc** [marxjmoura/admin4b#51]
Marx the linear-gradient feature is triggering a warning for the reason of using a deprecated syntax, the new way of using the grandiente's placement is by placing a reserved word **to** {and its positioning ex: top, right, left and bottom}. follow the link for help: https://developer.mozilla.org/en-US/docs/Web/CSS/linear-gradient

```
@mixin crossbrowser-linear-gradient($gradient...)
{
    background: nth($gradient, 1);
    background-image: -webkit-linear-gradient(to top, $gradient);
    background-image: -moz-linear-gradient(to top, $gradient);
    background-image: -ms-linear-gradient(to top, $gradient);
    background-image: -o-linear-gradient(to top, $gradient);
    background-image: linear-gradient(to top, $gradient);
}
```

**Comment by marxjmoura** [comment]
Solved in the version 1.1.0
