### ISSUE TITLE
Jquery plugins not defined

### ISSUE THREAD

**Issue by erickants** [marxjmoura/admin4b#54]
Version: 

> 1.1.1

Report: 

> The JS file doesn't work correctly in the Angular 6 and React frameworks

Error:

>  admin4b.min.js:1 Uncaught TypeError: Cannot read property 'fn' of undefined
>     at admin4b.min.js:1

**Comment by marxjmoura** [comment]
Thanks @erickants. The PR https://github.com/marxjmoura/admin4b/pull/55 should help to fix this problem.
