### ISSUE TITLE
Is it possible to split dist files

### ISSUE THREAD

**Issue by visavi** [marxjmoura/admin4b#73]
Please tell me whether it is possible to collect files separately
so that you can update your bootstrap yourself

or if I don’t need some components,
can you do it yourself?

**Comment by marxjmoura** [comment]
If you are using the minified files, you will not be able to split them.

If you can use Webpack or Gulp you can install the [NPM package](https://www.npmjs.com/package/admin4b) and select the components you want to use and update dependencies separately.
